name: update-bing-walpaper

on:
  schedule:
   - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v6
       with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
     - name: Set up Python
       uses: actions/setup-python@v5
       with:
        cache: 'pip'
        python-version: 3.12.12

     - name: Install Requirements
       run: |
         pip install -r requirements.txt
 
     - name: Update bing wallpaper
       working-directory: ./
       run: |
         python main.py
         
     - name: Commit and push json Files
       run: |
        if test -z "$(git status -s)"; then
          echo 'no commit'
          exit 0;
        else
          commit_message="自动拉取必应壁纸"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -a -m "${commit_message}"
          git push origin main
        fi
